'use client';
import {useEffect,useState,useMemo,useRef} from 'react';
import {ShieldCheck,LayoutDashboard,Users,CalendarDays,ClipboardCheck,TriangleAlert,FileBarChart,ArrowUpRight,ArrowRight,Plus,Search,Download,Upload,Check,Clock3,Building2,ChevronLeft,ChevronRight,Activity,MapPin,ArrowDownLeft,Radio,RefreshCw,CheckCircle2,Eye,FileSpreadsheet,UserRound,LogOut,ClipboardList,LockKeyhole,LoaderCircle} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarGroup,SidebarGroupLabel,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from '@/components/ui/table';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {sites,shifts,DEMO_DATE,type State,type Role,type Employee} from '@/lib/demo';
type View='Overview'|'Employees'|'Duty roster'|'Attendance'|'Incidents'|'Approvals'|'Reports'|'My duty';
const nav=[['Overview',LayoutDashboard],['Employees',Users],['Duty roster',CalendarDays],['Attendance',ClipboardCheck],['Incidents',TriangleAlert],['Approvals',ClipboardList],['Reports',FileBarChart]] as const;
const datestr=(d:string)=>new Date(d+'T12:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'});
const timestamp=(d:string)=>new Date(d).toLocaleString('en-IN',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Kolkata'});
function Choice({value,onChange,items,label}:{value:string;onChange:(s:string)=>void;items:string[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="command-select"><SelectValue/></SelectTrigger><SelectContent>{items.map(i=><SelectItem value={i} key={i}>{i}</SelectItem>)}</SelectContent></Select>}
function Avatar({name}:{name:string}){return <span className="person-avatar">{name.split(' ').map(s=>s[0]).slice(0,2).join('')}</span>}
function Badge({children,tone='green'}:{children:React.ReactNode;tone?:string}){return <span className={'status-badge '+tone}>{children}</span>}
function exportCSV(name:string,headers:string[],rows:(string|number)[][]){const cell=(v:string|number)=>'"'+String(v).replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const blob=new Blob(['\ufeff'+[headers,...rows].map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function parseCSV(source:string){const rows:string[][]=[];let row:string[]=[];let field='',quoted=false;for(let i=0;i<source.length;i++){const c=source[i];if(c==='"'){if(quoted&&source[i+1]==='"'){field+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(field.trim());field=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&source[i+1]==='\n')i++;row.push(field.trim());if(row.some(Boolean))rows.push(row);row=[];field=''}else field+=c}if(quoted)throw Error('An open quote was found. Check your CSV file.');row.push(field.trim());if(row.some(Boolean))rows.push(row);return rows}
function NavLinks({view,setView,role,pending}:{view:View;setView:(v:View)=>void;role:Role;pending:number}){const {isMobile,setOpenMobile}=useSidebar();return <SidebarMenu>{(role==='Employee'?[['My duty',UserRound] as const]:nav.filter(([n])=>!(role==='Site Lead'&&['Approvals','Reports'].includes(n)))).map(([n,Icon])=><SidebarMenuItem key={n}><SidebarMenuButton isActive={view===n} onClick={()=>{setView(n as View);if(isMobile)setOpenMobile(false)}} className="command-nav"><Icon size={18}/><span>{n}</span>{n==='Approvals'&&pending>0&&<b>{pending}</b>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu>}
export default function Command(){
 const [state,setState]=useState<State|null>(null),[version,setVersion]=useState(0),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const [view,setView]=useState<View>('Overview'),[role,setRole]=useState<Role>('Admin'),[site,setSite]=useState('All sites'),[day,setDay]=useState(DEMO_DATE),[query,setQuery]=useState(''),[status,setStatus]=useState('All statuses');
 const [modal,setModal]=useState<'employee'|'assign'|'incident'|'import'|null>(null),[person,setPerson]=useState<Employee|null>(null),[form,setForm]=useState<Record<string,string>>({}),[importRows,setImportRows]=useState<any[]>([]),[importError,setImportError]=useState(''),[modalError,setModalError]=useState('');
 const stateRef=useRef(state);stateRef.current=state;
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/operations',{cache:'no-store'});const d=await r.json() as {state:State;version:number;error?:string;message:string};if(!r.ok)throw Error(d.error||'Unable to complete request.');setState(d.state);setVersion(d.version)}catch(e){setError((e as Error).message||'Unable to connect. Try again.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{setQuery('');setStatus('All statuses')},[view]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'read_demo_roster',title:'Read the demonstration roster',description:'Read fictional SDC duty assignments for a date. Does not modify records.',inputSchema:{type:'object',properties:{date:{type:'string',pattern:'^\\d{4}-\\d{2}-\\d{2}$'}},required:['date'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:any){if(!input||typeof input.date!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(input.date)||isNaN(Date.parse(input.date)))throw Error('A valid date is required.');if(!stateRef.current)throw Error('Operations data is not loaded yet.');setDay(input.date);setView('Duty roster');return {demo:true,date:input.date,duties:stateRef.current.duties.filter(d=>d.date===input.date)}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[]);
 async function mutate(action:any){if(busy)return false;setBusy(true);setModalError('');try{const r=await fetch('/api/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({role,version,action})});const d=await r.json() as {state:State;version:number;error?:string;message:string};if(!r.ok)throw Error(d.error||'Unable to complete request.');setState(d.state);setVersion(d.version);toast.success(d.message);return true}catch(e){const msg=(e as Error).message;setModalError(msg);toast.error(msg);return false}finally{setBusy(false)}}
 function open(which:typeof modal){setForm({site:site==='All sites'?sites[1]:site,shift:shifts[0],date:day,designation:'Security Officer',priority:'Medium',employeeId:'',post:''});setImportRows([]);setImportError('');setModalError('');setModal(which)}
 const effectiveSite=role==='Site Lead'?sites[1]:site;
 const inSite=(s:string)=>effectiveSite==='All sites'||s===effectiveSite;
 const employees=state?.employees.filter(e=>inSite(e.site))||[];
 const duties=state?.duties.filter(d=>d.date===day&&inSite(d.site))||[];
 const incidents=state?.incidents.filter(i=>inSite(i.site))||[];
 const present=duties.filter(d=>d.attendance==='Present').length;
 const openIncidents=incidents.filter(i=>i.status==='Open');
 const pending=state?.leaves.filter(l=>l.status==='Pending').length||0;
 const active=employees.filter(e=>e.status==='Active').length;
 const coverage=active?Math.round(duties.length/active*100):0;
 const canManage=role==='Admin'||role==='Operations Manager';
 const nameOf=(id:string)=>state?.employees.find(e=>e.id===id)?.name||id;
 const filteredEmployees=employees.filter(e=>(`${e.name} ${e.id} ${e.designation}`.toLowerCase().includes(query.toLowerCase()))&&(status==='All statuses'||e.status===status));
 const filteredDuties=duties.filter(d=>(nameOf(d.employeeId)+' '+d.employeeId+' '+d.post).toLowerCase().includes(query.toLowerCase())&&(status==='All statuses'||d.attendance===status));
 function exportDuties(all=false){exportCSV(all?'sdc-duty-history.csv':`sdc-roster-${day}.csv`,['Employee ID','Name','Site','Post','Shift','Date','Attendance','Published at'],(all?state?.duties.filter(d=>inSite(d.site))||[]:filteredDuties).map(d=>[d.employeeId,nameOf(d.employeeId),d.site,d.post,d.shift,d.date,d.attendance,d.publishedAt]));toast.success('CSV export downloaded')}
 async function readImport(file:File|undefined){setImportError('');setImportRows([]);if(!file)return;if(file.size>250000){setImportError('Choose a CSV file smaller than 250 KB.');return}try{const rows=parseCSV((await file.text()).replace(/^\uFEFF/,''));if(rows.length<2)throw Error('The file needs a header and at least one assignment.');const expected=['employeeId','site','post','shift','date'];if(rows[0].join(',')!==expected.join(','))throw Error('Use the template headers: employeeId,site,post,shift,date.');if(rows.length>101)throw Error('Import up to 100 assignments at a time.');const seen=new Set<string>();const parsed=rows.slice(1).map((r,i)=>{if(r.length!==5)throw Error(`Row ${i+2}: expected 5 columns.`);const d=Object.fromEntries(expected.map((k,j)=>[k,r[j]]));if(!state?.employees.some(e=>e.id===d.employeeId&&e.status==='Active'))throw Error(`Row ${i+2}: unknown or inactive employee ID.`);if(!sites.slice(1).includes(d.site)||!shifts.includes(d.shift))throw Error(`Row ${i+2}: site or shift does not match the template.`);if(d.post.length<2||d.post.length>100||!/^\d{4}-\d{2}-\d{2}$/.test(d.date)||isNaN(Date.parse(d.date))||!new Date(d.date).toISOString().startsWith(d.date))throw Error(`Row ${i+2}: check the post and date.`);const key=d.employeeId+d.date;if(seen.has(key)||state.duties.some(x=>x.employeeId===d.employeeId&&x.date===d.date))throw Error(`Row ${i+2}: this employee already has a duty on that date.`);seen.add(key);return d});setImportRows(parsed)}catch(e){setImportError((e as Error).message)}}
 const empty=(title:string,description:string)=><div className="command-empty"><ClipboardList size={30}/><h3>{title}</h3><p>{description}</p></div>;
 return <SidebarProvider className="command-app" style={{'--sidebar-width':'236px'} as React.CSSProperties}><Sidebar className="command-sidebar"><SidebarHeader><a href="/" className="command-brand"><img className="command-crest" src="/brand/sdc-logo.png" alt="SDC Security Services eagle crest" width={46} height={46}/><div>SDC <b>COMMAND</b><small>CONNECTED OPERATIONS</small></div></a><div className="workspace-label"><Building2 size={17}/><span>SDC Security & Facility<small>Demonstration workspace</small></span></div></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>WORKSPACE</SidebarGroupLabel><NavLinks view={view} setView={setView} role={role} pending={pending}/></SidebarGroup><div className="sidebar-help"><span><ShieldCheck size={19}/> A clearer chain of command.</span><p>People, sites and daily decisions. Connected.</p><a href="/#technology">Discover the platform <ArrowUpRight size={14}/></a></div></SidebarContent><SidebarFooter><a className="back-website" href="/"><ArrowDownLeft size={16}/> Back to SDC website</a><div className="sidebar-profile"><Avatar name={role==='Employee'?'Arjun Rao':'SDC Demo'}/><span>{role==='Employee'?'Arjun Rao':'SDC workspace'}<small>{role} preview</small></span><Eye size={16}/></div></SidebarFooter></Sidebar>
 <SidebarInset className="command-inset"><header className="command-header"><div><SidebarTrigger/><span className="breadcrumb">Workspace <ChevronRight size={13}/> <b>{view}</b></span></div><div className="header-right"><span className="preview-label"><Eye size={13}/> Preview role</span><Choice label="Preview role" value={role} items={['Admin','Operations Manager','Site Lead','Employee']} onChange={r=>{setRole(r as Role);setView(r==='Employee'?'My duty':'Overview');setSite('All sites')}}/><span className="header-avatar">SD</span></div></header><div className="demo-banner"><span><span className="demo-pill">DEMO</span> Fictional people and sites. Changes are saved to your private demo.</span><span className="demo-date">Scenario · 21 September 2026</span></div><div className="command-main">
 <div className="page-heading"><div><div className="command-eyebrow">SDC COMMAND / {role==='Employee'?'YOUR WORKDAY':'OPERATIONS CENTRE'}</div><h1>{view==='Overview'?'Every detail. Under control.':view==='My duty'?'Ready for your next duty.':view}</h1><p>{({Overview:'A clear view of your people, your sites and what needs you today.',Employees:'The people behind every secure space.', 'Duty roster':'The right person, at the right post, at the right time.',Attendance:'Know who is on site. Follow up where it matters.',Incidents:'From the first report to a clear resolution.',Approvals:'Keep employee requests moving.',Reports:'Clear records, ready when you need them.','My duty':'Your assignment, shift details and recent duty history.'} as Record<View,string>)[view]}</p></div><div className="heading-actions">{view==='Employees'&&role==='Admin'?<button className="button brand-navy compact" onClick={()=>open('employee')}><Plus size={17}/> Add employee</button>:view==='Incidents'?<button className="button brand-navy compact" onClick={()=>open('incident')}><Plus size={17}/> Report incident</button>:canManage&&['Overview','Duty roster'].includes(view)?<><button className="button outline compact" onClick={()=>open('import')}><Upload size={16}/> Import roster</button><button className="button brand-navy compact" onClick={()=>open('assign')}><Plus size={17}/> Assign duty</button></>:null}</div></div>
 {role!=='Employee'&&<div className="global-filters"><div><MapPin size={15}/>{role==='Site Lead'?<span>Northstar Hospital · assigned site</span>:<Choice label="Filter by site" value={site} onChange={setSite} items={sites}/>}</div><div><CalendarDays size={15}/><input type="date" aria-label="Scenario date" value={day} onChange={e=>{if(e.target.value)setDay(e.target.value)}}/><button className="refresh-button" title="Refresh saved data" aria-label="Refresh saved data" onClick={load} disabled={loading}><RefreshCw size={15} className={loading?'spin':''}/></button></div></div>}
 {error?<div className="error-panel" role="alert"><TriangleAlert/><h3>We couldn’t load the workspace.</h3><p>{error}</p><button className="button brand-navy" onClick={load}>Try again</button></div>:!state?<div className="loading-panel" role="status"><LoaderCircle className="spin"/> Connecting your operations…</div>:<>
 {view==='Overview'&&<><div className="kpi-grid">{[[Users,'Active personnel',active,`${employees.length} in your employee directory`,'neutral'],[ShieldCheck,'Duty coverage',`${coverage}%`,`${duties.length} assigned · ${Math.max(0,active-duties.length)} awaiting assignment`,'green'],[ClipboardCheck,'Attendance',`${present}/${duties.length}`,`${duties.filter(d=>d.attendance==='Scheduled').length} awaiting check-in`,'neutral'],[TriangleAlert,'Open incidents',openIncidents.length,`${openIncidents.filter(i=>i.priority==='High').length} high priority · review required`,'amber']].map(([Icon,label,value,sub,tone]:any)=><article className={'kpi '+tone} key={label}><div><span>{label}</span><Icon size={18}/></div><strong>{value}</strong><p>{sub}</p></article>)}</div>
 <div className="dashboard-grid"><section className="command-panel site-health"><div className="panel-heading"><div><h2>Site deployment</h2><p>Coverage across your operating locations</p></div><button className="small-link" onClick={()=>setView('Duty roster')}>View roster <ArrowUpRight size={15}/></button></div><Table><TableHeader><TableRow><TableHead>Site</TableHead><TableHead>Assigned</TableHead><TableHead>Checked in</TableHead><TableHead>Coverage</TableHead></TableRow></TableHeader><TableBody>{sites.slice(1).filter(inSite).map(s=>{const scheduled=state.duties.filter(d=>d.site===s&&d.date===day);const a=state.employees.filter(e=>e.site===s&&e.status==='Active').length;return <TableRow key={s}><TableCell><div className="site-name"><span><Building2 size={18}/></span><div><strong>{s}</strong><small>Bengaluru · {s.includes('Hospital')?'Healthcare':s.includes('College')?'Education':'Corporate'}</small></div></div></TableCell><TableCell>{scheduled.length} <span className="muted">/ {a}</span></TableCell><TableCell>{scheduled.filter(d=>d.attendance==='Present').length} personnel</TableCell><TableCell><Badge tone={scheduled.length>=a?'green':'amber'}>{scheduled.length>=a?'Covered':'Needs attention'}</Badge></TableCell></TableRow>})}</TableBody></Table><div className="panel-foot"><ShieldCheck size={15}/>{Math.max(0,active-duties.length)>0?`${Math.max(0,active-duties.length)} active personnel need an assignment for this date.`:'All active personnel have an assignment for this date.'}</div></section>
 <section className="command-panel attention-panel"><div className="panel-heading"><div><h2>Needs your attention</h2><p>Small signals. Timely action.</p></div><span className="count-chip">{openIncidents.length+pending}</span></div>{openIncidents.slice(0,2).map(i=><button className="attention-item" key={i.id} onClick={()=>setView('Incidents')}><span className={'alert-icon '+(i.priority==='High'?'amber':'blue')}><TriangleAlert size={18}/></span><div><strong>{i.title}</strong><small>{i.site}</small></div><ChevronRight size={16}/></button>)}{canManage&&pending>0&&<button className="attention-item" onClick={()=>setView('Approvals')}><span className="alert-icon blue"><Clock3 size={18}/></span><div><strong>{pending} leave requests pending</strong><small>Review upcoming team availability</small></div><ChevronRight size={16}/></button>}{openIncidents.length===0&&pending===0&&<div className="quiet-state"><CheckCircle2/> You’re all caught up.</div>}</section>
 <section className="command-panel activity-panel"><div className="panel-heading"><div><h2>Operations activity</h2><p>An accountable trail of every update</p></div><Activity size={18} className="muted"/></div><div className="activity-list">{state.audit.slice(0,4).map((a,i)=><div className="activity-row" key={a.id}><span className={i===0?'activity-dot recent':'activity-dot'}/><div><strong>{a.action}</strong><small>{a.role} <span>·</span> {timestamp(a.time)} IST</small></div></div>)}</div></section>
 <section className="command-panel shift-panel"><div className="panel-heading"><div><h2>Shift distribution</h2><p>Scheduled personnel for {datestr(day)}</p></div><CalendarDays size={18} className="muted"/></div><div className="shift-bars">{shifts.map((s,i)=>{const n=duties.filter(d=>d.shift===s).length;return <div key={s}><div><span>{['Morning','Afternoon','Night'][i]}</span><b>{n}</b></div><div className="bar-track"><span style={{width:`${duties.length?n/duties.length*100:0}%`}}/></div><small>{s}</small></div>})}</div></section></div></>}
 {view==='Employees'&&<section className="command-panel"><div className="table-toolbar"><div className="search-field"><Search size={17}/><input aria-label="Search employees" placeholder="Search by name, ID or role…" value={query} onChange={e=>setQuery(e.target.value)}/></div><Choice label="Employee status" value={status} onChange={setStatus} items={['All statuses','Active','On leave']}/><button className="button outline compact" onClick={()=>exportCSV('sdc-employees.csv',['ID','Name','Role','Site','Status','Training'],filteredEmployees.map(e=>[e.id,e.name,e.designation,e.site,e.status,e.training]))}><Download size={16}/> Export</button></div><Table><TableHeader><TableRow>{['Employee','Role','Assigned site','Status','Training',''].map((t,i)=><TableHead key={i}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{filteredEmployees.map(e=><TableRow key={e.id}><TableCell><button className="person-link" onClick={()=>setPerson(e)}><Avatar name={e.name}/><span><strong>{e.name}</strong><small>{e.id}</small></span></button></TableCell><TableCell>{e.designation}</TableCell><TableCell>{e.site}</TableCell><TableCell><Badge tone={e.status==='Active'?'green':'gray'}>{e.status}</Badge></TableCell><TableCell><Badge tone={e.training==='Up to date'?'green':'amber'}>{e.training}</Badge></TableCell><TableCell><button className="icon-button" aria-label={`View ${e.name}`} onClick={()=>setPerson(e)}><ArrowUpRight size={17}/></button></TableCell></TableRow>)}</TableBody></Table>{!filteredEmployees.length&&empty('No employees found','Try a different name, status or site.')}<div className="table-footer">Showing {filteredEmployees.length} employees <span>Sample records · No real personnel data</span></div></section>}
 {['Duty roster','Attendance'].includes(view)&&<section className="command-panel"><div className="table-toolbar"><div className="search-field"><Search size={17}/><input aria-label="Search duty roster" placeholder="Search personnel or post…" value={query} onChange={e=>setQuery(e.target.value)}/></div><Choice label="Attendance status" value={status} onChange={setStatus} items={['All statuses','Present','Scheduled','Absent']}/><button className="button outline compact" onClick={()=>exportDuties()}><Download size={16}/> Export</button></div><div className="roster-date"><button aria-label="Previous day" onClick={()=>{const d=new Date(day+'T12:00:00');d.setDate(d.getDate()-1);setDay(d.toISOString().slice(0,10))}}><ChevronLeft size={17}/></button><strong>{datestr(day)}</strong><button aria-label="Next day" onClick={()=>{const d=new Date(day+'T12:00:00');d.setDate(d.getDate()+1);setDay(d.toISOString().slice(0,10))}}><ChevronRight size={17}/></button><span>{filteredDuties.length} assignments</span></div><Table><TableHeader><TableRow>{['Personnel','Site & post','Shift','Attendance',view==='Attendance'?'Update status':'Published'].map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{filteredDuties.map(d=><TableRow key={d.id}><TableCell><div className="person-link"><Avatar name={nameOf(d.employeeId)}/><span><strong>{nameOf(d.employeeId)}</strong><small>{d.employeeId}</small></span></div></TableCell><TableCell><strong className="cell-strong">{d.site}</strong><small className="cell-small">{d.post}</small></TableCell><TableCell><span className="shift-chip"><Clock3 size={13}/>{d.shift}</span></TableCell><TableCell><Badge tone={d.attendance==='Present'?'green':d.attendance==='Absent'?'red':'gray'}>{d.attendance}</Badge></TableCell><TableCell>{view==='Attendance'?<div className="row-actions"><button disabled={busy||d.attendance==='Present'} onClick={()=>mutate({type:'attendance',id:d.id,status:'Present'})}>Present</button><button className="danger-link" disabled={busy||d.attendance==='Absent'} onClick={()=>mutate({type:'attendance',id:d.id,status:'Absent'})}>Absent</button></div>:<span className="muted small">{timestamp(d.publishedAt)}</span>}</TableCell></TableRow>)}</TableBody></Table>{!filteredDuties.length&&empty('No assignments for this selection','Choose another date or publish a new duty assignment.')}<div className="table-footer"><span><LockKeyhole size={13}/> Duty history is preserved when a new roster is published.</span><span>All times IST</span></div></section>}
 {view==='Incidents'&&<section className="command-panel"><div className="table-toolbar"><h2>Incident register</h2><Choice label="Incident status" value={status} onChange={setStatus} items={['All statuses','Open','Resolved']}/></div><div className="incident-list">{incidents.filter(i=>status==='All statuses'||i.status===status).map(i=><div className="incident-card" key={i.id}><span className={'incident-icon '+(i.status==='Resolved'?'green':'amber')}>{i.status==='Resolved'?<CheckCircle2/>:<TriangleAlert/>}</span><div><div className="incident-meta"><span>{i.id}</span><Badge tone={i.priority==='High'?'red':i.priority==='Medium'?'amber':'gray'}>{i.priority} priority</Badge><Badge tone={i.status==='Open'?'amber':'green'}>{i.status}</Badge></div><h3>{i.title}</h3><p>{i.site} <span>·</span> {timestamp(i.time)} IST</p></div>{i.status==='Open'&&<button className="button outline compact" disabled={busy} onClick={()=>mutate({type:'resolve',id:i.id})}><Check size={16}/> Resolve</button>}</div>)}</div>{!incidents.filter(i=>status==='All statuses'||i.status===status).length&&empty('No incidents here','There are no incidents matching this status and site.')}</section>}
 {view==='Approvals'&&<section className="command-panel"><div className="table-toolbar"><div><h2>Leave requests</h2><p className="muted small">Review availability before approving time off.</p></div><Choice label="Request status" value={status} onChange={setStatus} items={['All statuses','Pending','Approved','Declined']}/></div><Table><TableHeader><TableRow>{['Employee','Leave type','Dates','Status','Decision'].map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{state.leaves.filter(l=>inSite(state.employees.find(e=>e.id===l.employeeId)?.site||'')&&(status==='All statuses'||l.status===status)).map(l=><TableRow key={l.id}><TableCell><div className="person-link"><Avatar name={nameOf(l.employeeId)}/><strong>{nameOf(l.employeeId)}</strong></div></TableCell><TableCell>{l.type}</TableCell><TableCell>{datestr(l.from)} — {datestr(l.to)}</TableCell><TableCell><Badge tone={l.status==='Approved'?'green':l.status==='Declined'?'red':'amber'}>{l.status}</Badge></TableCell><TableCell>{l.status==='Pending'?<div className="row-actions"><button disabled={busy} onClick={()=>mutate({type:'leave',id:l.id,status:'Approved'})}>Approve</button><button className="danger-link" disabled={busy} onClick={()=>mutate({type:'leave',id:l.id,status:'Declined'})}>Decline</button></div>:<span className="muted">Reviewed</span>}</TableCell></TableRow>)}</TableBody></Table>{!state.leaves.filter(l=>inSite(state.employees.find(e=>e.id===l.employeeId)?.site||'')&&(status==='All statuses'||l.status===status)).length&&empty('No requests here','There are no requests matching your selection.')}</section>}
 {view==='Reports'&&<><div className="report-grid">{[[Users,'Employee directory','Current headcount, deployment sites and training status.',()=>exportCSV('sdc-headcount.csv',['ID','Name','Role','Site','Status'],employees.map(e=>[e.id,e.name,e.designation,e.site,e.status]))],[CalendarDays,'Duty history','Every published assignment with its date and attendance.',()=>exportDuties(true)],[ClipboardCheck,'Attendance register',`Check-in status for ${datestr(day)} at the selected sites.`,()=>exportDuties()],[Activity,'Activity audit','A dated record of changes made in this demonstration.',()=>exportCSV('sdc-activity.csv',['Action','Role','Timestamp'],state.audit.map(a=>[a.action,a.role,a.time]))]].map(([Icon,title,desc,action]:any)=><article className="command-panel report-card" key={title}><span><Icon size={24}/></span><h2>{title}</h2><p>{desc}</p><button className="button outline compact" onClick={action}><Download size={16}/> Download CSV</button></article>)}</div><div className="report-note"><ShieldCheck size={20}/><div><strong>A foundation for audit-ready operations.</strong><p>These exports contain sample operational data. Payroll calculations, statutory filings and production identity integrations are outside this demonstration.</p></div></div></>}
 {view==='My duty'&&<><div className="employee-welcome"><Avatar name="Arjun Rao"/><div><h2>Arjun Rao</h2><p>SDC-0101 · Site Supervisor · Northstar Hospital</p></div><Badge>Employee preview</Badge></div>{state.duties.filter(d=>d.employeeId==='SDC-0101').length===0?empty('No duties assigned','Your upcoming assignments will appear here.'):<div className="personal-duties">{state.duties.filter(d=>d.employeeId==='SDC-0101').sort((a,b)=>b.date.localeCompare(a.date)).map(d=><section className="command-panel personal-duty" key={d.id}><div className="panel-heading"><h2>{datestr(d.date)}</h2><Badge tone={d.attendance==='Present'?'green':'gray'}>{d.attendance}</Badge></div><div className="personal-duty-info"><Building2/><div><small>YOUR DUTY LOCATION</small><h3>{d.site}</h3><p>{d.post}</p></div></div><div className="personal-shift"><span><Clock3 size={18}/> Shift timing</span><strong>{d.shift} IST</strong></div><div className="panel-foot"><ShieldCheck size={15}/> Report to your site supervisor before taking charge.</div></section>)}</div>}<div className="report-note"><Eye size={20}/><p>This role preview shows the employee experience. Production staff login and identity verification will be configured before rollout.</p></div></>}
 </>}
 <footer className="command-footer"><span><ShieldCheck size={13}/> SDC Command · Clarity at every level</span><span>Private client demonstration</span></footer></div></SidebarInset>
 <Dialog open={modal!==null} onOpenChange={v=>{if(!busy&&!v)setModal(null)}}><DialogContent className={'sdc-dialog '+(modal==='import'?'import-dialog':'')}><DialogHeader><div className="dialog-icon">{modal==='employee'?<Users/>:modal==='incident'?<TriangleAlert/>:<CalendarDays/>}</div><DialogTitle>{modal==='employee'?'Add a team member':modal==='assign'?'Put your people in place.':modal==='incident'?'Report an incident':'From duty sheet to clear assignments.'}</DialogTitle><DialogDescription>{modal==='import'?'Import a CSV roster, review the matched employees, then publish. Photo recognition is planned and is not enabled in this demo.':'Changes are saved to your private demonstration. Please use fictional information.'}</DialogDescription></DialogHeader>
 {modal==='import'?<div className="import-flow"><button className="template-link" onClick={()=>exportCSV('sdc-roster-template.csv',['employeeId','site','post','shift','date'],[['SDC-0101',sites[1],'Main entrance',shifts[0],'2026-09-22']])}><Download size={16}/> Download the CSV template</button><label className="upload-zone"><Upload size={28}/><strong>Choose a weekly roster</strong><span>CSV only · up to 100 assignments · 250 KB</span><input aria-label="Upload CSV roster" type="file" accept=".csv,text/csv" onChange={e=>readImport(e.target.files?.[0])}/></label>{importError&&<p role="alert" className="inline-error">{importError}</p>}{importRows.length>0&&<><div className="import-success"><CheckCircle2 size={18}/>{importRows.length} assignments matched. Ready for your review.</div><div className="import-preview"><Table><TableHeader><TableRow><TableHead>Employee</TableHead><TableHead>Site / post</TableHead><TableHead>Date & shift</TableHead></TableRow></TableHeader><TableBody>{importRows.map((r,i)=><TableRow key={i}><TableCell>{nameOf(r.employeeId)}</TableCell><TableCell>{r.site}<small className="cell-small">{r.post}</small></TableCell><TableCell>{r.date}<small className="cell-small">{r.shift}</small></TableCell></TableRow>)}</TableBody></Table></div><button className="button brand-navy" disabled={busy} onClick={async()=>{if(await mutate({type:'assign',duties:importRows})){setDay(importRows[0].date);setModal(null);setView('Duty roster')}}}>{busy?'Publishing…':`Publish ${importRows.length} assignments`}<ArrowRight size={17}/></button></>}{modalError&&<p role="alert" className="inline-error">{modalError}</p>}</div>:<form className="sdc-form" onSubmit={async e=>{e.preventDefault();let action;if(modal==='employee')action={type:'employee',name:form.name,designation:form.designation,site:form.site};else if(modal==='incident')action={type:'incident',site:form.site,title:form.title,priority:form.priority};else action={type:'assign',duties:[{employeeId:form.employeeId,site:form.site,post:form.post,shift:form.shift,date:form.date}]};if(await mutate(action)){if(modal==='assign')setDay(form.date);setModal(null)}}}>
 {modal==='employee'?<><label>Full name<input required maxLength={100} value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})} placeholder="e.g. Amit Sharma"/></label><label>Designation<Choice label="Designation" value={form.designation} onChange={v=>setForm({...form,designation:v})} items={['Security Officer','Site Supervisor','Facility Associate']}/></label></>:modal==='incident'?<><label>What happened?<textarea required minLength={2} maxLength={100} value={form.title||''} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Briefly describe the issue" rows={3}/></label><label>Priority<Choice label="Priority" value={form.priority} onChange={v=>setForm({...form,priority:v})} items={['Low','Medium','High']}/></label></>:<label>Employee<Select value={form.employeeId} onValueChange={v=>setForm({...form,employeeId:v})} required><SelectTrigger className="command-select full-width" aria-label="Employee"><SelectValue placeholder="Select active employee"/></SelectTrigger><SelectContent>{state?.employees.filter(e=>e.status==='Active').map(e=><SelectItem key={e.id} value={e.id}>{e.name} · {e.id}</SelectItem>)}</SelectContent></Select></label>}
 <label>Deployment site<Choice label="Deployment site" value={form.site} onChange={v=>setForm({...form,site:v})} items={role==='Site Lead'?[sites[1]]:sites.slice(1)}/></label>
 {modal==='assign'&&<><label>Post<input required minLength={2} maxLength={100} value={form.post} onChange={e=>setForm({...form,post:e.target.value})} placeholder="e.g. Main entrance"/></label><div className="form-two"><label>Duty date<input required type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Shift<Choice label="Shift" value={form.shift} onChange={v=>setForm({...form,shift:v})} items={shifts}/></label></div></>}
 {modalError&&<p role="alert" className="inline-error">{modalError}</p>}<button className="button brand-navy" type="submit" disabled={busy||modal==='assign'&&!form.employeeId}>{busy?<><LoaderCircle className="spin" size={17}/> Saving…</>:<>{modal==='employee'?'Add employee':modal==='assign'?'Publish assignment':'Save incident'}<ArrowRight size={17}/></>}</button></form>}
 </DialogContent></Dialog>
 <Dialog open={person!==null} onOpenChange={v=>{if(!v)setPerson(null)}}><DialogContent className="sdc-dialog"><DialogHeader><Avatar name={person?.name||''}/><DialogTitle>{person?.name}</DialogTitle><DialogDescription>{person?.id} · {person?.designation}</DialogDescription></DialogHeader><div className="employee-detail"><p>Assigned site<strong>{person?.site}</strong></p><p>Joined<strong>{person&&datestr(person.joined)}</strong></p><p>Training<strong>{person?.training}</strong></p><p>Status<Badge tone={person?.status==='Active'?'green':'gray'}>{person?.status}</Badge></p></div><h3 className="detail-heading">Duty history</h3>{state?.duties.filter(d=>d.employeeId===person?.id).map(d=><div className="detail-duty" key={d.id}><CalendarDays size={18}/><div><strong>{datestr(d.date)} · {d.shift}</strong><small>{d.site} / {d.post}</small></div><Badge tone={d.attendance==='Present'?'green':'gray'}>{d.attendance}</Badge></div>)}{!state?.duties.some(d=>d.employeeId===person?.id)&&<p className="muted small">No assignments published yet.</p>}</DialogContent></Dialog><Toaster position="bottom-right" richColors/>
 </SidebarProvider>
}
