import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
const load=async path=>import('data:text/javascript;base64,'+Buffer.from(ts.transpileModule(readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString('base64'));
const {seed,sites,shifts}=await load('lib/demo.ts');
const {savePlan,publishPlan,validatePlan,weekDuties,weekStart}=await load('lib/deployment.ts');
const site=sites[1],week='2026-09-21',now='2026-09-21T10:00:00Z';let count=0;const id=()=>`test-${++count}`;
const placement=(employeeId='SDC-0104',date='2026-09-22',post='Main entrance',shift=shifts[0])=>({employeeId,date,post,shift,site});
let state=seed();const original=structuredClone(state.duties);const before=weekDuties(state,site,week);
savePlan(state,site,week,[...before,placement()],'Operations Manager',now);
assert.deepEqual(state.duties,original,'Draft does not alter live duties');
let result=publishPlan(state,site,week,'Senior Manager',now,id);
assert.equal(result.changes.added,1);assert.equal(state.deploymentDrafts.length,0);assert.equal(state.rosterPublications.length,1);
assert.deepEqual(state.duties.filter(d=>d.site!==site),original.filter(d=>d.site!==site));
assert.deepEqual(state.duties.find(d=>d.id==='D-0'),original.find(d=>d.id==='D-0'));
assert.equal(state.rosterPublications[0].before.length,before.length);
let plan=weekDuties(state,site,week).map(d=>d.employeeId==='SDC-0104'?{...d,post:'Visitor reception'}:d);
savePlan(state,site,week,plan,'Admin',now);result=publishPlan(state,site,week,'Admin',now,id);assert.deepEqual(result.changes,{added:1,removed:1});
assert(validatePlan(state,site,week,plan.filter(d=>d.id!=='D-0')).some(s=>s.includes('locked')));
assert(validatePlan(state,site,week,[...plan,placement('SDC-0104','2026-09-22','Emergency block')]).some(s=>s.includes('one shift')));
assert(validatePlan(state,site,week,[...plan,placement('SDC-0105','2026-09-21','Visitor reception')]).some(s=>s.includes('one shift')));
assert(validatePlan(state,site,week,[...plan,placement('SDC-0112')]).some(s=>s.includes('on leave')));
state.leaves.push({id:'test',employeeId:'SDC-0102',from:'2026-09-23',to:'2026-09-23',status:'Approved',type:'Casual'});
assert(validatePlan(state,site,week,[...plan,placement('SDC-0102','2026-09-23')]).some(s=>s.includes('approved leave')));
assert(validatePlan(state,site,week,[...plan,placement('SDC-0104','2026-09-23','Main entrance',shifts[2]),placement('SDC-0104','2026-09-24')]).some(s=>s.includes('8 hours')));
assert(validatePlan(state,site,week,[...plan,placement('SDC-0102','2026-09-22','Visitor reception')]).some(s=>s.includes('Two people')));
assert(validatePlan(state,site,week,[...plan,placement('unknown')]).some(s=>s.includes('Unknown')));
assert.equal(weekStart('2026-09-27'),week);
const scheduled=plan.find(d=>d.employeeId==='SDC-0104');
savePlan(state,site,week,plan.filter(d=>d!==scheduled),'Admin',now);
state.duties.find(d=>d.employeeId==='SDC-0104').attendance='Present';
assert.throws(()=>publishPlan(state,site,week,'Admin',now,id),/changed/);
state=seed();state.duties=[];plan=[placement('SDC-0101'),placement('SDC-0102','2026-09-22','Emergency block')];
savePlan(state,site,week,plan,'Admin',now);publishPlan(state,site,week,'Admin',now,id);
const swapped=plan.map((p,i)=>({...p,employeeId:plan[1-i].employeeId}));
savePlan(state,site,week,swapped,'Admin',now);publishPlan(state,site,week,'Admin',now,id);
assert.equal(state.duties.find(d=>d.post==='Main entrance').employeeId,'SDC-0102');
savePlan(state,site,week,[],'Admin',now);result=publishPlan(state,site,week,'Admin',now,id);assert.equal(result.gaps,63);assert.equal(state.duties.length,0);
console.log('PASS: draft isolation, publish, move, swap, unassign, gaps, retained IDs and attendance, cross-site conflicts, double booking, leave, rest, unknown people, Monday week and stale publication.');
