// Local-only integration test. Uses fictional records and clears its published test week.
import assert from 'node:assert/strict';
const base='http://localhost:5173';const headers={'Cookie':'__sites_local_auth=1','Content-Type':'application/json','Origin':base};
const read=async()=>{const r=await fetch(base+'/api/operations',{headers});assert.equal(r.status,200);return r.json()};
let data=await read();const site='Northstar Hospital',week='2035-01-01';
const request=async(action,role='Admin',version=data.version)=>{const r=await fetch(base+'/api/operations',{method:'POST',headers,body:JSON.stringify({role,version,action})});const body=await r.json();if(r.ok)data=body;return {status:r.status,body}};
const duty={employeeId:'SDC-0104',site,post:'Main entrance',date:week,shift:'06:00 – 14:00'};
const save={type:'save-deployment',site,week,placements:[duty]};
assert.equal((await fetch(base+'/api/operations')).status,401);
assert.equal((await request(save,'Site Lead')).status,403);
assert.equal((await request(save,'Employee')).status,403);
const initial=data.state.duties;
assert.equal((await request(save,'Senior Manager')).status,200);
assert.deepEqual(data.state.duties,initial);
const reread=await read();assert.equal(reread.state.deploymentDrafts.find(d=>d.week===week).placements.length,1);
assert.equal((await request(save,'Admin',data.version-1)).status,409);
assert.equal((await request({...save,placements:[duty,{...duty,post:'Visitor reception'}]})).status,409);
assert.equal((await request({type:'publish-deployment',site,week},'Operations Manager')).status,200);
assert(data.state.duties.some(d=>d.date===week&&d.employeeId===duty.employeeId));
assert(data.state.rosterPublications.some(p=>p.week===week&&p.after.length===1));
assert(data.state.audit[0].action.includes('Deployment published'));
assert.equal((await request({...save,placements:[]})).status,200);
assert.equal((await request({type:'publish-deployment',site,week})).status,200);
assert(!data.state.duties.some(d=>d.date===week&&d.site===site));
assert.equal((await request(save)).status,200);
assert.equal((await request({type:'discard-deployment',site,week})).status,200);
assert(!data.state.deploymentDrafts.some(d=>d.week===week&&d.site===site));
assert.equal((await read()).version,data.version);
console.log('PASS: authenticated storage, role restrictions, Senior Manager editing, draft persistence, stale version, server conflicts, publish to roster, snapshot/audit history and discard.');
