import assert from 'node:assert/strict';import postgres from 'postgres';import {randomUUID} from 'node:crypto';import {seedFoundation} from '../../scripts/seed-foundation.mjs';
const url=process.env.SDC_TEST_DATABASE_URL;if(!url||!['localhost','127.0.0.1'].includes(new URL(url).hostname))throw Error('Local disposable database required');const sql=postgres(url,{max:5,onnotice:()=>{}}),ids=Object.fromEntries(['admin','ops','guard','outsider','client'].map(k=>[k,randomUUID()]));const as=(key,fn)=>sql.begin(async tx=>{await tx.unsafe('set local role authenticated');await tx`select set_config('request.jwt.claim.sub',${ids[key]},true)`;return fn(tx)});
try{for(const [k,id] of Object.entries(ids))await sql`insert into auth.users(id,email) values(${id},${k+'@test.invalid'})`;const f=await seedFoundation(sql,{ownerId:ids.admin,code:'ROSTER-'+randomUUID()}),t=f.tenant.id;for(const [k,r] of [['ops','operations_manager'],['guard','employee'],['client','client_user']])await sql`insert into memberships(tenant_id,user_id,display_name,role) values(${t},${ids[k]},${k},${r})`;const [guard]=await sql`select id from memberships where user_id=${ids.guard}`;const [p]=await sql`select * from posts where tenant_id=${t} order by created_at limit 1`;const [sh]=await sql`select * from shift_templates where tenant_id=${t} order by starts_at limit 1`;const [site]=await sql`select * from sites where tenant_id=${t} and id=${p.site_id}`;const [client]=await sql`select id from memberships where user_id=${ids.client}`;await sql`insert into member_scopes(tenant_id,membership_id,client_id) values(${t},${client.id},${site.client_id})`;
const [e]=await as('admin',tx=>tx`insert into employees(tenant_id,employee_code,full_name,grade_id,category,joined_on,membership_id) values(${t},'ROSTER-1','Test guard',${p.grade_id},'full_time','2026-01-01',${guard.id}) returning *`);const [e2]=await as('admin',tx=>tx`insert into employees(tenant_id,employee_code,full_name,grade_id,category,joined_on) values(${t},'ROSTER-2','Test second guard',${p.grade_id},'full_time','2026-01-01') returning *`);
await sql`update staffing_requirements set deleted_at=now(),row_version=row_version+1 where tenant_id=${t} and post_id=${p.id} and shift_id=${sh.id}`;await as('admin',tx=>tx`insert into staffing_requirements(tenant_id,post_id,shift_id,headcount,effective_from) values(${t},${p.id},${sh.id},2,'2026-09-01')`);
const assign=(who,emp,date,slot=1)=>as(who,tx=>tx`select roster_assign(${t},${emp},${p.id},${sh.id},${date},${slot},'Database test') as result`);
await assert.rejects(()=>assign('guard',e.id,'2026-10-01'),/operations managers/);await assert.rejects(()=>assign('outsider',e.id,'2026-10-01'),/operations managers/);
const [one]=await assign('ops',e.id,'2026-10-01'),a=one.result;
assert.equal((await as('guard',tx=>tx`select roster_board(${t},null,'2026-10-01',7) as x`))[0].x.length,0);
assert.equal((await as('client',tx=>tx`select roster_board(${t},${p.site_id},'2026-10-01',7) as x`))[0].x.length,0);
await assert.rejects(()=>assign('ops',e.id,'2026-10-01',2),/overlaps/);
await assert.rejects(()=>assign('ops',e2.id,'2026-10-01'),/duplicate key/);
await assert.rejects(()=>as('ops',tx=>tx`select roster_remove(${t},${a.id},99,'Invalid stale save')`),/Roster changed/);
const [published]=await as('ops',tx=>tx`select roster_publish(${t},${p.site_id},'2026-10-01') as result`);assert.equal(published.result.revision,1);
assert.equal((await as('guard',tx=>tx`select roster_board(${t},null,'2026-10-01',7) as x`))[0].x.length,1);
assert.equal((await as('client',tx=>tx`select roster_board(${t},${p.site_id},'2026-10-01',7) as x`))[0].x.length,1);
assert.equal((await as('guard',tx=>tx`select * from workforce_notifications where tenant_id=${t}`)).length,1);
await as('guard',tx=>tx`select roster_acknowledge(${t},${a.id})`);assert((await sql`select acknowledged_at from roster_live where tenant_id=${t} and id=${a.id}`)[0].acknowledged_at);
assert.equal((await as('client',tx=>tx`select * from roster_assignments where tenant_id=${t}`)).length,0);
assert.equal((await as('guard',tx=>tx`select * from roster_assignments where tenant_id=${t}`)).length,0);
const [working]=await sql`select * from roster_assignments where tenant_id=${t} and id=${a.id}`;
await as('ops',tx=>tx`select roster_assign(${t},${e2.id},${p.id},${sh.id},'2026-10-01',1,'Replace working draft',${a.id},${working.row_version})`);
assert.equal((await sql`select employee_id from roster_live where tenant_id=${t} and id=${a.id}`)[0].employee_id,e.id,'Working edits must not change published duty');
await as('ops',tx=>tx`select roster_publish(${t},${p.site_id},'2026-10-01')`);
assert.equal((await sql`select employee_id from roster_live where tenant_id=${t} and id=${a.id}`)[0].employee_id,e2.id);
assert((await as('guard',tx=>tx`select * from workforce_notifications where tenant_id=${t}`)).some(n=>n.title==='Duty roster revised'));
const [course]=await as('admin',tx=>tx`insert into training_courses(tenant_id,code,title,category,mandatory_for) values(${t},'MAND','Mandatory induction','induction',array['full_time']) returning *`);
await assert.rejects(()=>assign('ops',e2.id,'2026-10-02'),/Missing certification/);
await as('admin',tx=>tx`select roster_assign(${t},${e2.id},${p.id},${sh.id},'2026-10-02',1,'Emergency assignment',null,null,'Documented emergency reviewed by admin')`);
const [cand]=await as('ops',tx=>tx`select roster_candidates(${t},${p.id},${sh.id},'2026-10-03') as result`);assert(cand.result.every(c=>c.reasons.some(r=>r.startsWith('Missing certification'))));
await assert.rejects(()=>as('guard',tx=>tx`select roster_candidates(${t},${p.id},${sh.id},'2026-10-03')`),/Access denied/);
const races=await Promise.allSettled([as('admin',tx=>tx`select roster_assign(${t},${e.id},${p.id},${sh.id},'2026-10-03',1,'Concurrent test',null,null,'Documented emergency reviewed by admin')`),as('admin',tx=>tx`select roster_assign(${t},${e2.id},${p.id},${sh.id},'2026-10-03',1,'Concurrent test',null,null,'Documented emergency reviewed by admin')`)]);assert.equal(races.filter(r=>r.status==='fulfilled').length,1);
console.log('PASS roster: role/site isolation, draft privacy, overlap/slot conflict, stale writes, publish, notifications, self acknowledgement, certificate block, admin audited override, concurrent slot protection.');
}finally{await sql.end()}
