import assert from 'node:assert/strict';import postgres from 'postgres';import {randomUUID} from 'node:crypto';import {seedFoundation} from '../../scripts/seed-foundation.mjs';
const url=process.env.SDC_TEST_DATABASE_URL;if(!url||!['localhost','127.0.0.1'].includes(new URL(url).hostname))throw Error('Local test database required');const sql=postgres(url,{onnotice:()=>{}}),ids=Object.fromEntries(['admin','client','outsider'].map(k=>[k,randomUUID()]));const as=(u,fn)=>sql.begin(async tx=>{await tx.unsafe('set local role authenticated');await tx`select set_config('request.jwt.claim.sub',${ids[u]},true)`;return fn(tx)});
try{for(const [k,id] of Object.entries(ids))await sql`insert into auth.users(id,email) values(${id},${k+'@test.invalid'})`;const f=await seedFoundation(sql,{ownerId:ids.admin,code:'FIELD-'+randomUUID()}),t=f.tenant.id,s=f.sites[0].id;const [m]=await sql`insert into memberships(tenant_id,user_id,display_name,role) values(${t},${ids.client},'Test client','client_user') returning *`;await sql`insert into member_scopes(tenant_id,membership_id,site_id) values(${t},${m.id},${s})`;
const [r]=await as('admin',tx=>tx`insert into field_findings(tenant_id,site_id,kind,category,title,description,severity,likelihood,remedy,responsible_party,target_date) values(${t},${s},'weakness','Lighting','Poor lighting','Perimeter lighting needs repair','high',4,'Repair lights','client',current_date+7) returning *`);
assert.equal((await as('client',tx=>tx`select * from field_findings where tenant_id=${t}`)).length,1);assert.equal((await as('outsider',tx=>tx`select * from field_findings where tenant_id=${t}`)).length,0);
await assert.rejects(()=>as('client',tx=>tx`insert into field_findings(tenant_id,site_id,kind,category,title,description,severity,likelihood,remedy,responsible_party,target_date) values(${t},${s},'weakness','Lighting','Wrong actor','Wrong actor','high',4,'Repair lights','client',current_date+7)`),/row-level security/);
await assert.rejects(()=>as('admin',tx=>tx`update field_findings set status='closed',row_version=row_version+1 where tenant_id=${t} and id=${r.id}`),/workflow action/);
const act=async(who,status)=>{const [v]=await sql`select row_version from field_findings where tenant_id=${t} and id=${r.id}`;return as(who,tx=>tx`select field_transition(${t},'findings',${r.id},${v.row_version},${status},'Test workflow comment','Client Signer','127.0.0.1')`)};
await act('admin','flagged');await assert.rejects(()=>act('admin','acknowledged'),/client must/);await act('client','acknowledged');await act('client','in_progress');await assert.rejects(()=>act('client','resolved'),/Upload evidence/);
const evidence=randomUUID();await as('client',tx=>tx`insert into field_evidence(id,tenant_id,site_id,entity_type,entity_id,file_name,mime_type,size_bytes,object_path) values(${evidence},${t},${s},'findings',${r.id},'proof.jpg','image/jpeg',100,${t+'/'+s+'/'+evidence+'/proof.jpg'})`);
await act('client','resolved');await assert.rejects(()=>act('client','verified'),/Supervisor/);await act('admin','verified');await act('admin','closed');const [score]=await as('client',tx=>tx`select site_security_score(${t},${s}) as result`);assert.equal(score.result.score,100);
await assert.rejects(()=>as('outsider',tx=>tx`select site_security_score(${t},${s})`),/Access denied/);
const [incident]=await as('admin',tx=>tx`insert into field_incidents(tenant_id,site_id,title,category,severity,description) values(${t},${s},'Test incident','Safety','low','Test description') returning *`);
await assert.rejects(()=>as('client',tx=>tx`select field_transition(${t},'incidents',${incident.id},0,'acknowledged','Invalid client workflow')`),/Supervisor/);
assert((await as('client',tx=>tx`select * from field_events where tenant_id=${t}`)).length>=6);console.log('PASS field: scoped risk reads, denied client writes, guarded lifecycle, named client acknowledgement, evidence requirement, supervisor-only verification, score recalculation, incident roles.');
}finally{await sql.end()}
