import assert from 'node:assert/strict';import postgres from 'postgres';import {randomUUID} from 'node:crypto';import {seedFoundation} from '../../scripts/seed-foundation.mjs';
const url=process.env.SDC_TEST_DATABASE_URL;if(!url||!['localhost','127.0.0.1'].includes(new URL(url).hostname))throw Error('Local test DB only');const sql=postgres(url,{onnotice:()=>{}}),admin=randomUUID(),client=randomUUID();const as=(u,fn)=>sql.begin(async tx=>{await tx.unsafe('set local role authenticated');await tx`select set_config('request.jwt.claim.sub',${u},true)`;return fn(tx)});
try{await sql`insert into auth.users(id,email) values(${admin},'admin@test.invalid'),(${client},'client@test.invalid')`;const f=await seedFoundation(sql,{ownerId:admin,code:'CCTV-'+randomUUID()}),t=f.tenant.id,s=f.sites[0],doc=randomUUID();const [m]=await sql`insert into memberships(tenant_id,user_id,display_name,role) values(${t},${client},'Test client','client_user') returning *`;await sql`insert into member_scopes(tenant_id,membership_id,site_id) values(${t},${m.id},${s.id})`;await as(admin,tx=>tx`insert into foundation_documents(id,tenant_id,client_id,site_id,category,file_name,mime_type,size_bytes,object_path) values(${doc},${t},${s.client_id},${s.id},'sop','Consent.pdf','application/pdf',100,${t+'/'+doc+'/Consent.pdf'})`);
const [consent]=await as(admin,tx=>tx`insert into cctv_consents(tenant_id,site_id,title,authorized_cameras,permitted_roles,purpose,starts_on,ends_on,signed_document_id) values(${t},${s.id},'Mock consent',array['Gate camera'],array['admin','client_user'],'Test monitoring',current_date-1,current_date+1,${doc}) returning *`);
await assert.rejects(()=>as(admin,tx=>tx`insert into cctv_cameras(tenant_id,site_id,consent_id,title,location,stream_type) values(${t},${s.id},${consent.id},'Unauthorized camera','Gate','mock')`),/explicitly cover/);
const [camera]=await as(admin,tx=>tx`insert into cctv_cameras(tenant_id,site_id,consent_id,title,location,stream_type) values(${t},${s.id},${consent.id},'Gate camera','Gate','mock') returning *`);
const [session]=await as(client,tx=>tx`select cctv_view(${t},${camera.id},'Review site perimeter') as x`);assert.equal(session.x.viewer,'Test client');await as(client,tx=>tx`select cctv_view(${t},${camera.id},'',${session.x.session_id},false)`);
await as(admin,tx=>tx`update cctv_consents set revoked_at=now(),row_version=row_version+1 where tenant_id=${t} and id=${consent.id}`);
await assert.rejects(()=>as(client,tx=>tx`select cctv_view(${t},${camera.id},'',${session.x.session_id},false)`),/revoked/);
await as(client,tx=>tx`select cctv_view(${t},${camera.id},'',${session.x.session_id},true)`);
const logs=await as(client,tx=>tx`select * from cctv_access_log where tenant_id=${t}`);assert.equal(logs.length,1);assert(logs[0].ended_at);
console.log('PASS CCTV: camera-specific consent, scoped client access, logged reason/viewer, renewal, immediate revoked-consent denial and closing audit.');
}finally{await sql.end()}
