create table public.notification_deliveries(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,notification_id uuid not null references public.workforce_notifications(id),membership_id uuid not null,channel text not null check(channel in ('email','sms','whatsapp')),language text not null default 'English',status text not null default 'pending' check(status in ('pending','processing','delivered','simulated','failed')),attempts integer not null default 0,next_attempt_at timestamptz not null default now(),lease_token uuid,last_error text,provider_reference text,created_at timestamptz not null default now(),completed_at timestamptz,foreign key(tenant_id,membership_id) references public.memberships(tenant_id,id),unique(notification_id,channel));
alter table public.notification_deliveries enable row level security;revoke all on public.notification_deliveries from anon,authenticated;grant select on public.notification_deliveries to authenticated;
create policy delivery_scope on public.notification_deliveries for select to authenticated using(sdc_private.is_admin(tenant_id) or exists(select 1 from public.memberships m where m.tenant_id=notification_deliveries.tenant_id and m.id=notification_deliveries.membership_id and m.user_id=auth.uid() and m.active));
create index delivery_pending on public.notification_deliveries(tenant_id,next_attempt_at) where status in ('pending','processing');
create function sdc_private.enqueue_notification() returns trigger language plpgsql security definer set search_path='' as $$begin
 insert into public.notification_deliveries(tenant_id,notification_id,membership_id,channel,language)
 select new.tenant_id,new.id,new.membership_id,x.channel,p.language from public.notification_preferences p cross join lateral(values('email',p.email),('sms',p.sms),('whatsapp',p.whatsapp))x(channel,enabled) where p.tenant_id=new.tenant_id and p.membership_id=new.membership_id and x.enabled;
 return new;end $$;
revoke all on function sdc_private.enqueue_notification() from public,anon,authenticated;
create trigger queue_delivery after insert on public.workforce_notifications for each row execute function sdc_private.enqueue_notification();
create function public.claim_notification_deliveries(p_tenant uuid,p_token text) returns jsonb language plpgsql security definer set search_path='' as $$declare result jsonb;begin
 if not exists(select 1 from sdc_private.job_tokens where tenant_id=p_tenant and token_hash=encode(sha256(convert_to(p_token,'UTF8')),'hex')) then raise exception 'Invalid worker authorization' using errcode='42501';end if;
 with candidates as(select id from public.notification_deliveries where tenant_id=p_tenant and status in ('pending','processing') and next_attempt_at<=now() and attempts<5 order by created_at limit 20 for update skip locked),claimed as(update public.notification_deliveries d set status='processing',attempts=attempts+1,lease_token=gen_random_uuid(),next_attempt_at=now()+interval '5 minutes' from candidates c where d.id=c.id returning d.*)
 select coalesce(jsonb_agg(jsonb_build_object('id',d.id,'lease',d.lease_token,'channel',d.channel,'language',d.language,'title',n.title,'body',n.body,'href',n.href,'destination',case when d.channel='email' then case when u.email_confirmed_at is not null then u.email end else case when u.phone_confirmed_at is not null then u.phone end end,'enabled',coalesce(b.external_notifications_enabled,false) and not t.is_demo and m.active,'attempts',d.attempts)),'[]') into result from claimed d join public.workforce_notifications n on n.id=d.notification_id join public.memberships m on m.tenant_id=d.tenant_id and m.id=d.membership_id join auth.users u on u.id=m.user_id join public.tenants t on t.id=d.tenant_id left join public.business_settings b on b.tenant_id=d.tenant_id;
 return result;end $$;
create function public.finish_notification_delivery(p_tenant uuid,p_token text,p_id uuid,p_lease uuid,p_status text,p_reference text default '',p_error text default '') returns void language plpgsql security definer set search_path='' as $$begin
 if not exists(select 1 from sdc_private.job_tokens where tenant_id=p_tenant and token_hash=encode(sha256(convert_to(p_token,'UTF8')),'hex')) then raise exception 'Invalid worker authorization' using errcode='42501';end if;
 if p_status not in ('delivered','simulated','failed') then raise exception 'Invalid delivery outcome';end if;
 update public.notification_deliveries set status=case when p_status='failed' and attempts<5 then 'pending' else p_status end,provider_reference=left(p_reference,200),last_error=left(p_error,300),completed_at=case when p_status<>'failed' or attempts>=5 then now() end,next_attempt_at=now()+make_interval(mins=>attempts*5),lease_token=null where tenant_id=p_tenant and id=p_id and status='processing' and lease_token=p_lease;
 if not found then raise exception 'Delivery lease has expired';end if;end $$;
revoke all on function public.claim_notification_deliveries(uuid,text),public.finish_notification_delivery(uuid,text,uuid,uuid,text,text,text) from public,anon,authenticated;grant execute on function public.claim_notification_deliveries(uuid,text),public.finish_notification_delivery(uuid,text,uuid,uuid,text,text,text) to anon;
