create or replace function public.roster_candidates(p_tenant uuid,p_post uuid,p_shift uuid,p_date date,p_query text default '',p_offset integer default 0) returns jsonb language plpgsql security definer set search_path='' as $$declare target public.sites;post public.posts;shift public.shift_templates;begin
 if auth.uid() is null or not sdc_private.is_operator(p_tenant) then raise exception 'Access denied' using errcode='42501';end if;
 select * into post from public.posts where tenant_id=p_tenant and id=p_post and deleted_at is null;select * into target from public.sites where tenant_id=p_tenant and id=post.site_id;select * into shift from public.shift_templates where tenant_id=p_tenant and id=p_shift;
 return coalesce((select jsonb_agg(to_jsonb(x)) from(select e.id,e.full_name,e.employee_code,e.category,sdc_private.roster_reasons(p_tenant,e.id,p_post,p_shift,p_date) as reasons,
 (select count(*) from public.roster_assignments r where r.tenant_id=p_tenant and r.employee_id=e.id and r.site_id=post.site_id and r.deleted_at is null) as previous_shifts,
 (select round(extract(epoch from ((p_date+shift.starts_at) at time zone 'Asia/Kolkata')-max(r.ends_at))/3600,1) from public.roster_assignments r where r.tenant_id=p_tenant and r.employee_id=e.id and r.ends_at<=(p_date+shift.starts_at) at time zone 'Asia/Kolkata' and r.deleted_at is null) as rest_hours,
 (select coalesce(sum(extract(epoch from r.ends_at-r.starts_at)/3600),0) from public.roster_assignments r where r.tenant_id=p_tenant and r.employee_id=e.id and r.work_date>=date_trunc('week',p_date)::date and r.work_date<date_trunc('week',p_date)::date+7 and r.deleted_at is null) as weekly_hours,
 (select round((6371*2*asin(sqrt(least(1,power(sin(radians((s.latitude-target.latitude)::double precision)/2),2)+cos(radians(target.latitude::double precision))*cos(radians(s.latitude::double precision))*power(sin(radians((s.longitude-target.longitude)::double precision)/2),2)))))::numeric,1) from public.employee_postings p join public.sites s on s.tenant_id=p.tenant_id and s.id=p.site_id where p.tenant_id=p_tenant and p.employee_id=e.id and p.deleted_at is null and p.starts_on<=p_date and (p.ends_on is null or p.ends_on>=p_date) order by p.starts_on desc limit 1) as distance_km,
 (select round(greatest(0,shift.duration_minutes-480)/60.0*salary.overtime_hour_paise) from public.employee_salary_structures salary where salary.tenant_id=p_tenant and salary.employee_id=e.id and salary.deleted_at is null and salary.rule_approved and salary.starts_on<=p_date and (salary.ends_on is null or salary.ends_on>=p_date) order by salary.starts_on desc limit 1) as estimated_overtime_paise
 from public.employees e where e.tenant_id=p_tenant and e.deleted_at is null and e.status='active' and e.grade_id=post.grade_id and (e.full_name ilike '%'||left(p_query,80)||'%' or e.employee_code ilike '%'||left(p_query,80)||'%')
 order by jsonb_array_length(sdc_private.roster_reasons(p_tenant,e.id,p_post,p_shift,p_date)),previous_shifts desc,distance_km nulls last,estimated_overtime_paise nulls last,e.employee_code,e.id limit 50 offset greatest(0,least(p_offset,100000)))x),'[]');
end $$;
