create function public.training_matrix(p_tenant uuid,p_query text default '',p_offset integer default 0,p_site uuid default null,p_client uuid default null,p_grade uuid default null) returns jsonb language plpgsql stable security definer set search_path='' as $$declare people jsonb;total integer;begin
 if auth.uid() is null or not sdc_private.is_member(p_tenant) then raise exception 'Access denied' using errcode='42501';end if;
 with scoped as(select e.* from public.employees e where e.tenant_id=p_tenant and e.deleted_at is null and (sdc_private.is_trainer(p_tenant) or sdc_private.can_employee(p_tenant,e.id)) and (p_grade is null or e.grade_id=p_grade) and (e.full_name ilike '%'||left(p_query,80)||'%' or e.employee_code ilike '%'||left(p_query,80)||'%') and (p_site is null and p_client is null or exists(select 1 from public.employee_postings p join public.sites s on s.tenant_id=p.tenant_id and s.id=p.site_id where p.tenant_id=p_tenant and p.employee_id=e.id and p.deleted_at is null and p.starts_on<=current_date and (p.ends_on is null or p.ends_on>=current_date) and (p_site is null or p.site_id=p_site) and (p_client is null or s.client_id=p_client)))) select count(*) into total from scoped;
 select coalesce(jsonb_agg(to_jsonb(x)),'[]') into people from(
 select e.id,e.full_name,e.employee_code,e.category,
 (select coalesce(sum(n.hours_completed),0) from public.training_enrollments n where n.tenant_id=p_tenant and n.employee_id=e.id and n.deleted_at is null) as training_hours,
 (select coalesce(jsonb_object_agg(a.course_id,a.expires_on::text),'{}') from(select distinct on(course_id) course_id,coalesce(expires_on,'9999-12-31'::date) expires_on from public.training_awards where tenant_id=p_tenant and employee_id=e.id and revoked_at is null and deleted_at is null order by course_id,expires_on desc nulls first)a) as certificates,
 case when not exists(select 1 from public.training_courses c where c.tenant_id=p_tenant and c.deleted_at is null and e.category=any(c.mandatory_for) and not exists(select 1 from public.training_awards a where a.tenant_id=p_tenant and a.employee_id=e.id and a.course_id=c.id and a.revoked_at is null and a.deleted_at is null and (a.expires_on is null or a.expires_on>=current_date))) then 'Deployable'
 when exists(select 1 from public.training_attempts a where a.tenant_id=p_tenant and a.employee_id=e.id and a.submitted_at is null) then 'Assessment'
 when exists(select 1 from public.training_enrollments n where n.tenant_id=p_tenant and n.employee_id=e.id and n.attendance='present' and n.deleted_at is null) then 'In training' else 'Enrolled' end as pipeline
 from public.employees e where e.tenant_id=p_tenant and e.deleted_at is null and (sdc_private.is_trainer(p_tenant) or sdc_private.can_employee(p_tenant,e.id)) and (p_grade is null or e.grade_id=p_grade) and (e.full_name ilike '%'||left(p_query,80)||'%' or e.employee_code ilike '%'||left(p_query,80)||'%') and (p_site is null and p_client is null or exists(select 1 from public.employee_postings p join public.sites s on s.tenant_id=p.tenant_id and s.id=p.site_id where p.tenant_id=p_tenant and p.employee_id=e.id and p.deleted_at is null and p.starts_on<=current_date and (p.ends_on is null or p.ends_on>=current_date) and (p_site is null or p.site_id=p_site) and (p_client is null or s.client_id=p_client))) order by e.employee_code,e.id limit 50 offset greatest(0,least(p_offset,100000)))x;
 return jsonb_build_object('rows',people,'total',total);
end $$;
revoke all on function public.training_matrix(uuid,text,integer,uuid,uuid,uuid) from public,anon;grant execute on function public.training_matrix(uuid,text,integer,uuid,uuid,uuid) to authenticated;
create index if not exists training_awards_matrix on public.training_awards(tenant_id,employee_id,course_id,expires_on desc) where revoked_at is null and deleted_at is null;
