import assert from 'node:assert/strict';import postgres from 'postgres';import {randomUUID} from 'node:crypto';import {seedFoundation} from '../../scripts/seed-foundation.mjs';
const url=process.env.SDC_TEST_DATABASE_URL;if(!url||!['localhost','127.0.0.1'].includes(new URL(url).hostname))throw Error('Local database required');const sql=postgres(url,{onnotice:()=>{}}),admin=randomUUID(),client=randomUUID();const as=(id,fn)=>sql.begin(async tx=>{await tx.unsafe('set local role authenticated');await tx`select set_config('request.jwt.claim.sub',${id},true)`;return fn(tx)});
try{await sql`insert into auth.users(id,email) values(${admin},'admin@test.invalid'),(${client},'client@test.invalid')`;const f=await seedFoundation(sql,{ownerId:admin,code:'BUSINESS-'+randomUUID()}),t=f.tenant.id,s=f.sites[0];await sql`insert into business_settings(tenant_id,legal_name,gstin,billing_address,sac_code) values(${t},'Fictional agency','29ABCDE1234F1Z5','Fictional test address','9985')`;const [contract]=await sql`select * from contracts where tenant_id=${t} and client_id=${s.client_id} limit 1`;const [rate]=await sql`select * from rate_card_lines where tenant_id=${t} and contract_id=${contract.id} limit 1`;const [e]=await as(admin,tx=>tx`insert into employees(tenant_id,employee_code,full_name,grade_id,category,joined_on) values(${t},'BILL-1','Fictional billing guard',${rate.grade_id},'full_time','2026-01-01') returning *`);const [cm]=await sql`insert into memberships(tenant_id,user_id,display_name,role) values(${t},${client},'Test client','client_user') returning *`;await sql`insert into member_scopes(tenant_id,membership_id,client_id) values(${t},${cm.id},${s.client_id})`;
await as(admin,tx=>tx`insert into employee_attendance(tenant_id,employee_id,site_id,work_date,status,approval) values(${t},${e.id},${s.id},'2026-09-01','present','pending')`);
await assert.rejects(()=>as(admin,tx=>tx`select billing_generate(${t},${contract.id},'2026-09-01','2026-10-15',0,'Test zero tax',true)`),/Approve the client muster/);
await as(admin,tx=>tx`update employee_attendance set approval='approved',row_version=row_version+1 where tenant_id=${t} and employee_id=${e.id}`);
const [result]=await as(admin,tx=>tx`select billing_generate(${t},${contract.id},'2026-09-01','2026-10-15',0,'Test zero tax',true) as invoice`),i=result.invoice;assert.equal(i.total_paise,Math.round(Number(rate.monthly_rate_paise)/30));assert.equal((await as(client,tx=>tx`select * from billing_summary where tenant_id=${t}`)).length,0);
await as(admin,tx=>tx`select billing_issue(${t},${i.id},0,'issued')`);assert.equal((await as(client,tx=>tx`select * from billing_summary where tenant_id=${t}`)).length,1);
await assert.rejects(()=>as(client,tx=>tx`select billing_receive(${t},${i.id},'payment',1,0,'BAD','2026-09-21','Wrong role')`),/Finance access/);
await as(admin,tx=>tx`select billing_receive(${t},${i.id},'payment',${i.total_paise},0,'PAID-1','2026-09-21','Full payment')`);const [balance]=await as(client,tx=>tx`select balance_paise from billing_summary where tenant_id=${t}`);assert.equal(Number(balance.balance_paise),0);
await assert.rejects(()=>as(admin,tx=>tx`select billing_receive(${t},${i.id},'payment',1,0,'PAID-2','2026-09-21','Overpayment')`),/exceeds/);
const [candidate]=await as(admin,tx=>tx`insert into recruitment_candidates(tenant_id,full_name,phone,source,status,verification_notes) values(${t},'Fictional candidate','0000000000','Referral','ready','Verified test documents') returning *`);const [converted]=await as(admin,tx=>tx`select recruitment_convert(${t},${candidate.id},${rate.grade_id},'NEW-01','2026-09-21') as id`);assert(converted.id);await assert.rejects(()=>as(admin,tx=>tx`select recruitment_convert(${t},${candidate.id},${rate.grade_id},'NEW-02','2026-09-21')`),/verification/);
await assert.rejects(()=>as(admin,tx=>tx`update recruitment_candidates set status='sourced',employee_id=null,row_version=row_version+1 where tenant_id=${t} and id=${candidate.id}`),/read only/);
await assert.rejects(()=>as(client,tx=>tx`select run_operational_checks(${t},'invalid')`),/authorization/);const [check]=await as(admin,tx=>tx`select run_operational_checks(${t}) as result`);assert.equal(typeof check.result.notifications_created,'number');console.log('PASS business: approved muster, exact paise totals, hidden drafts, client issued invoice, finance-only receipts, overpayment guard, immutable conversion and authorized jobs.');
}finally{await sql.end()}
